server:
  port: 0
spring:
  application:
    name: customer-ws
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: sa
  jpa:
    show-sql: true
  h2:
    console:
      path: /h2
      settings:
        web-allow-others: true   
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://192.168.49.1:8761/eureka
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
management:
  endpoints:
    web:
      exposure:
        include:
        - '*'
