server:
  port: 9091
spring:
  application:
    name: product-ws
  datasource:
    url: jdbc:h2:mem:testdb;
    password: sa
    username: sa
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true