server:
  port: 0
spring:
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
  datasource:
    url: jdbc:mysql://localhost:3306/hr
    username: root
    password: root
  application:
    name: product-ws
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
  zipkin:
    base-url: http://localhost:9411
  boot:
    admin:
      client:
        url:
        - http://localhost:9000
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://192.168.49.1:8761/eureka
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}